app/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request,current_app
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User, Item ,Image
from app.forms import RegistrationForm, LoginForm, ImageForm
import os
import uuid
from prometheus_client import Summary
from google.cloud import storage
# os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="tete-426803-fcea6282bee1.json"
main = Blueprint('main', __name__)
users = Blueprint('users', __name__)
def extract_filename(url):
    filename = os.path.basename(url)
    name, ext = os.path.splitext(filename)
    # UUID 부분과 파일 이름 부분을 분리
    original_name = "_".join(name.split('_')[1:])
    return original_name

def upload_to_gcs(file, bucket_name):
    client = storage.Client()
    # client = storage.Client.from_service_account_json(current_app.config['GOOGLE_APPLICATION_CREDENTIALS'])
    bucket = client.bucket(bucket_name)
    # 원래 파일 이름을 사용하여 새로운 파일 이름 생성
    filename = file.filename
    new_filename = f"{uuid.uuid4()}_{filename}"
    blob = bucket.blob(f"images/{new_filename}")
    blob.upload_from_file(file)
    # 객체를 공개합니다.
    blob.make_public()
    return blob.public_url

def delete_from_gcs(url):
    client = storage.Client()
    # client = storage.Client.from_service_account_json(current_app.config['GOOGLE_APPLICATION_CREDENTIALS'])
    bucket_name = current_app.config['GCS_BUCKET_NAME']
    bucket = client.bucket(bucket_name)
    # URL에서 객체 이름 추출
    object_name = url.split(f"https://storage.googleapis.com/{bucket_name}/")[-1]
    blob = bucket.blob(object_name)
    blob.delete()

# Create a metric to track time spent and requests made.
REQUEST_TIME = Summary('request_processing_seconds', 'Time spent processing request')


@main.route('/')
@main.route('/home')
@REQUEST_TIME.time()
def home():
    
    return render_template('index.html')

@main.route('/fashion')
@REQUEST_TIME.time()
def fashion():
    images = Image.query.all()
    images_with_filenames = [(image.id, image.url, extract_filename(image.url)) for image in images]
    return render_template('it.html', images=images_with_filenames)
    

@main.route('/electronic')
@REQUEST_TIME.time()
def electronic():
    images = Image.query.all()
    images_with_filenames = [(image.url, extract_filename(image.url)) for image in images]
    return render_template('infa.html', images=images_with_filenames)

@main.route('/jewellery')
@REQUEST_TIME.time()
def jewellery():
    return render_template('jewellery.html')

@users.route('/login', methods=['GET', 'POST'])
@REQUEST_TIME.time()
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', form=form)

@users.route('/register', methods=['GET', 'POST'])
@REQUEST_TIME.time()
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, phone_number=form.phone_number.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/logout')
@REQUEST_TIME.time()
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/cart')
@REQUEST_TIME.time()
@login_required
def cart():
    # cart = current_user.cart
    # if not cart:
    #     cart = Cart(user_id=current_user.id)
    #     db.session.add(cart)
    #     db.session.commit()
    return render_template('cart.html', cart=cart)

# @main.route('/add_to_cart/<int:item_id>', methods=['POST'])
# @login_required
# def add_to_cart(item_id):
#     item = Item.query.get_or_404(item_id)
#     cart = current_user.cart
#     if not cart:
#         cart = Cart(user_id=current_user.id)
#         db.session.add(cart)
#         db.session.commit()

#     cart_item = CartItem.query.filter_by(cart_id=cart.id, item_id=item.id).first()
#     if cart_item:
#         cart_item.quantity += 1
#     else:
#         cart_item = CartItem(cart_id=cart.id, item_id=item.id, quantity=1)
#         db.session.add(cart_item)
    
#     db.session.commit()
#     flash(f'Item {item.name} added to cart', 'success')
#     return redirect(url_for('main.home'))

@main.route('/search')
@REQUEST_TIME.time()
def search():
    query = request.args.get('query')
    items = Item.query.filter(Item.name.like(f'%{query}%')).all()
    return render_template('search_results.html', items=items, query=query)


# @users.route('/add_image', methods=['GET', 'POST'])
# @REQUEST_TIME.time()
# def add_image():
#     form = ImageForm()
#     if form.validate_on_submit():
#         new_image = Image(url=form.url.data)
#         db.session.add(new_image)
#         db.session.commit()
#         return redirect(url_for('main.home'))
#     return render_template('add_image.html', form=form)

@main.route('/add_image', methods=['GET', 'POST'])
@login_required
def add_image():
    form = ImageForm()
    if form.validate_on_submit():
        file = form.image.data
        url = upload_to_gcs(file, current_app.config['GCS_BUCKET_NAME'])
        new_image = Image(url=url)
        db.session.add(new_image)
        db.session.commit()
        flash('Image added successfully!', 'success')
        return redirect(url_for('main.fashion'))
    return render_template('adi.html', form=form)

@main.route('/delete_image/<int:image_id>', methods=['POST'])
@login_required
def delete_image(image_id):
    image = Image.query.get_or_404(image_id)
    delete_from_gcs(image.url)
    db.session.delete(image)
    db.session.commit()
    flash('Image has been deleted!', 'success')
    return redirect(url_for('main.fashion'))

app/templates/adi.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
    <h1>Add a New Image</h1>
    <form method="POST" action="{{ url_for('main.add_image') }}" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.image.label }}
            {{ form.image(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

app/templates/base.back.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- basic -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- mobile metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="initial-scale=1, maximum-scale=1">
        <!-- site metas -->
        <title>Home</title>
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- bootstrap css -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <!-- style css -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
        <!-- Responsive-->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') }}">
        <!-- fevicon -->
        <link rel="icon" href="{{ url_for('static', filename='images/fevicon.png') }}" type="image/gif" />
        <!-- Scrollbar Custom CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.mCustomScrollbar.min.css') }}">
        <!-- Tweaks for older IEs-->
        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
        <!-- fonts -->
        <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
        <!-- font awesome -->
        <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- owl stylesheets -->
        <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.theme.default.min.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    </head>
<body>
    <div class="banner_bg_main">
        <!-- header top section start -->
        <div class="container">
            <div class="header_section_top">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="custom_menu">
                            <ul>
                                <li><a href="#">Best Sellers</a></li>
                                <li><a href="#">Gift Ideas</a></li>
                                <li><a href="#">New Releases</a></li>
                                <li><a href="#">Today's Deals</a></li>
                                <li><a href="#">Customer Service</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>


<!-- logo section start -->
<div class="logo_section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="logo"><a href="{{ url_for('main.home') }}"><img src="{{ url_for('static', filename='images/logo.png') }}"></a></div>
            </div>
        </div>
    </div>
</div>
<!-- logo section end -->
<!-- header section start -->
<div class="header_section">
    <div class="container">
        <div class="containt_main">
            <div id="mySidenav" class="sidenav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <a href="{{ url_for('main.home') }}">Home</a>
                <a href="{{ url_for('main.fashion') }}">제품관리</a>
                <a href="{{ url_for('main.electronic') }}">확인</a>
                <a href="{{ url_for('main.jewellery') }}">Jewellery</a>
            </div>
            <span class="toggle_icon" onclick="openNav()"><img src="{{ url_for('static', filename='images/toggle-icon.png') }}"></span>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All Category 
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </div>
            <div class="main">
                <!-- Another variation with a button -->
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search this blog">
                    <div class="input-group-append">
                        <button class="btn btn-secondary" type="button" style="background-color: #f26522; border-color:#f26522 ">
                        <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="header_box">
                <div class="lang_box ">
                    <a href="#" title="Language" class="nav-link" data-toggle="dropdown" aria-expanded="true">
                    <img src="{{ url_for('static', filename='images/flag-uk.png') }}" alt="flag" class="mr-2 " title="United Kingdom"> English <i class="fa fa-angle-down ml-2" aria-hidden="true"></i>
                    </a>
                    <div class="dropdown-menu ">
                        <a href="#" class="dropdown-item">
                        <img src="{{ url_for('static', filename='images/flag-france.png') }}" class="mr-2" alt="flag">
                        French
                        </a>
                    </div>
                </div>
                <div class="login_menu">
                    <ul>
                        {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('users.cart') }}">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            <span class="padding_10">Cart</span></a>
                        </li>
                        <li><a href="{{ url_for('users.logout') }}">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <span class="padding_10">logout</span></a>
                        </li>
                        
                        {% else %}
                        <li><a href="{{ url_for('users.cart') }}">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            <span class="padding_10">Cart</span></a>
                        </li>
                        <li><a href="{{ url_for('users.login') }}">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <span class="padding_10">signin</span></a>
                        </li>
                        <li><a href="{{ url_for('users.register') }}">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <span class="padding_10">signup</span></a>
                        </li>

                        {% endif %}


                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- header section end -->


    
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="row">
            <div class="col-md-12">
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
<!-- footer section start -->
<div class="footer_section layout_padding">
    <div class="container">
        <div class="footer_logo"><a href="index.html"><img src="{{ url_for('static', filename='images/footer-logo.png') }}"></a></div>
        <div class="input_bt">
            <input type="text" class="mail_bt" placeholder="Your Email" name="Your Email">
            <span class="subscribe_bt" id="basic-addon2"><a href="#">Subscribe</a></span>
        </div>
        <div class="footer_menu">
            <ul>
                <li><a href="#">Best Sellers</a></li>
                <li><a href="#">Gift Ideas</a></li>
                <li><a href="#">New Releases</a></li>
                <li><a href="#">Today's Deals</a></li>
                <li><a href="#">Customer Service</a></li>
            </ul>
        </div>
        <div class="location_main">Help Line  Number : <a href="#">+1 1800 1200 1200</a></div>
    </div>
</div>
<!-- footer section end -->
<!-- copyright section start -->
<div class="copyright_section">
    <div class="container">
        <p class="copyright_text">© 2020 All Rights Reserved. Design by <a href="https://html.design">Free html  Templates</a></p>
    </div>
</div>
<!-- copyright section end -->
<!-- Javascript files-->
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-3.0.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/plugin.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.mCustomScrollbar.concat.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/custom.js') }}"></script>
<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
</script>
</body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- basic -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- mobile metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="initial-scale=1, maximum-scale=1">
        <!-- site metas -->
        <title>Home</title>
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- bootstrap css -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <!-- style css -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
        <!-- Responsive-->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') }}">
        <!-- fevicon -->
        <link rel="icon" href="{{ url_for('static', filename='images/fevicon.png') }}" type="image/gif" />
        <!-- Scrollbar Custom CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.mCustomScrollbar.min.css') }}">
        <!-- Tweaks for older IEs-->
        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
        <!-- fonts -->
        <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
        <!-- font awesome -->
        <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- owl stylesheets -->
        <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.theme.default.min.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    </head>
<body>
    <div class="banner_bg_main">
        <!-- header top section start -->
        <div class="container">
            <div class="header_section_top">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="custom_menu">
                            <ul>
                                <li><a href="#"></a></li>
                                <li><a href="#"></a></li>
                                <li><a href="#"></a></li>
                                <li><a href="#"></a></li>
                                <li><a href="#"></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>


<!-- logo section start -->
<div class="logo_section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="logo"><a href="{{ url_for('main.home') }}"><img src="{{ url_for('static', filename='images/logo.png') }}"></a></div>
            </div>
        </div>
    </div>
</div>
<!-- logo section end -->
<!-- header section start -->
<div class="header_section">
    <div class="container">
        <div class="containt_main">
            <div id="mySidenav" class="sidenav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <a href="{{ url_for('main.home') }}">Home</a>
                <a href="{{ url_for('main.fashion') }}">제품관리</a>
                <a href="{{ url_for('main.electronic') }}">확인</a>
                <a href="{{ url_for('main.jewellery') }}">Jewellery</a>
            </div>
            <span class="toggle_icon" onclick="openNav()"><img src="{{ url_for('static', filename='images/toggle-icon.png') }}"></span>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All Category 
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </div>
            <div class="main">
                <!-- Another variation with a button -->
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search this blog">
                    <div class="input-group-append">
                        <button class="btn btn-secondary" type="button" style="background-color: #f26522; border-color:#f26522 ">
                        <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="header_box">
                <div class="lang_box ">
                    <a href="#" title="Language" class="nav-link" data-toggle="dropdown" aria-expanded="true">
                    <img src="{{ url_for('static', filename='images/flag-uk.png') }}" alt="flag" class="mr-2 " title="United Kingdom"> English <i class="fa fa-angle-down ml-2" aria-hidden="true"></i>
                    </a>
                    <div class="dropdown-menu ">
                        <a href="#" class="dropdown-item">
                        <img src="{{ url_for('static', filename='images/korea.png') }}" class="mr-2" alt="flag">
                        Korea
                        </a>
                    </div>
                </div>
                <div class="login_menu">
                    <ul>
                        {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('users.cart') }}">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            <span class="padding_10">Cart</span></a>
                        </li>
                        <li><a href="{{ url_for('users.logout') }}">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <span class="padding_10">logout</span></a>
                        </li>
                        
                        {% else %}
                        <li><a href="{{ url_for('users.cart') }}">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            <span class="padding_10">장바구니</span></a>
                        </li>
                        <li><a href="{{ url_for('users.login') }}">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <span class="padding_10">로그인</span></a>
                        </li>
                        <li><a href="{{ url_for('users.register') }}">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <span class="padding_10">회원가입</span></a>
                        </li>

                        {% endif %}


                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- header section end -->


    
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="row">
            <div class="col-md-12">
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
<!-- footer section start -->
<div class="footer_section layout_padding">
    <div class="container">
        <div class="footer_logo"><a href="index.html"><img src="{{ url_for('static', filename='images/footer-logo.png') }}"></a></div>
        <div class="input_bt">
            <input type="text" class="mail_bt" placeholder="Your Email" name="Your Email">
            <span class="subscribe_bt" id="basic-addon2"><a href="#">Subscribe</a></span>
        </div>
        <div class="footer_menu">
            <ul>
                <li><a href="#">Best Sellers</a></li>
                <li><a href="#">Gift Ideas</a></li>
                <li><a href="#">New Releases</a></li>
                <li><a href="#">Today's Deals</a></li>
                <li><a href="#">Customer Service</a></li>
            </ul>
        </div>
        <div class="location_main">Help Line  Number : <a href="#">+1 1800 1200 1200</a></div>
    </div>
</div>
<!-- footer section end -->
<!-- copyright section start -->
<div class="copyright_section">
    <div class="container">
        <p class="copyright_text">© 2020 All Rights Reserved. Design by <a href="https://html.design">Free html  Templates</a></p>
    </div>
</div>
<!-- copyright section end -->
<!-- Javascript files-->
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-3.0.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/plugin.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.mCustomScrollbar.concat.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/custom.js') }}"></script>
<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
</script>
</body>
</html>

app/templates/cart.html
{% extends "base.html" %}
{% block title %}Cart{% endblock %}
{% block content %}
    <h2>Your Cart</h2>
    {% if cart.items %}
        <ul>
            {% for cart_item in cart.items %}
                <li>
                    <img src="{{ url_for('static', filename='images/' ~ cart_item.item.image_file) }}" alt="{{ cart_item.item.name }}" width="100">
                    <p>{{ cart_item.item.name }} - Quantity: {{ cart_item.quantity }}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Your cart is empty.</p>
    {% endif %}
{% endblock %}

app/templates/it.html
{% extends "base.html" %}
{% block content %}

<li class="nav-item">
    <a class="btn btn-primary btn-lg nav-link text-white" href="{{ url_for('main.add_image') }}">Add Image</a>
</li>
<div class="container mt-4">
    <h1 class="fashion_taital">Man & Woman Fashion</h1>
    <div class="fashion_section_2">
        <div class="row">
            {% for image_id, image_url, filename in images %}
            <div class="col-lg-4 col-sm-4 mb-4">
                <div class="box_main">
                    <h4 class="shirt_text">{{ filename }}</h4>
                    <div class="tshirt_img"><img src="{{ image_url }}" alt="Fashion Item" class="img-fluid"></div>
                    <form method="POST" action="{{ url_for('main.delete_image', image_id=image_id) }}">
                        <button type="submit" class="btn btn-danger mt-2">Delete</button>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
    <div class="form-container">
        <h2>Register</h2>
        <form method="POST" action="{{ url_for('users.register') }}">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label(class="form-label") }}
                {{ form.username(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.phone_number.label(class="form-label") }}
                {{ form.phone_number(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-label") }}
                {{ form.password(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-label") }}
                {{ form.confirm_password(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/search_results.html
{% extends "base.html" %}
{% block title %}Search Results{% endblock %}
{% block content %}
    <h2>Search Results for "{{ query }}"</h2>
    {% if items %}
        <ul>
        {% for item in items %}
            <li>{{ item.name }} - ${{ item.price }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No items found for your query.</p>
    {% endif %}
{% endblock %}